package com.mindware.vista;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.*;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;

public class AddGrupo extends Window {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TextField edtGrupo;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;
	@AutoGenerated
	private Button btnCerrar;
	@AutoGenerated
	private Button btnGuardar;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private TwinColSelect twinColSelect_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public AddGrupo() {
		buildMainLayout();
		
		setContent(mainLayout);
		//setCompositionRoot(mainLayout);

		btnCerrar.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				close();
				
			}
		});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("400px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("400px");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1, "top:60.0px;right:-1.0px;left:20.0px;");
		
		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		mainLayout.addComponent(horizontalLayout_4, "top:320.0px;left:18.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Nombre de Grupo:");
		mainLayout.addComponent(label_1, "top:22.0px;left:20.0px;");
		
		// edtGrupo
		edtGrupo = new TextField();
		edtGrupo.setImmediate(false);
		edtGrupo.setWidth("353px");
		edtGrupo.setHeight("24px");
		mainLayout.addComponent(edtGrupo, "top:20.0px;left:123.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("260px");
		verticalLayout_1.setMargin(false);
		
		// twinColSelect_1
		twinColSelect_1 = new TwinColSelect();
		twinColSelect_1.setImmediate(false);
		twinColSelect_1.setWidth("570px");
		twinColSelect_1.setHeight("250px");
		verticalLayout_1.addComponent(twinColSelect_1);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("560px");
		horizontalLayout_4.setHeight("40px");
		horizontalLayout_4.setMargin(false);
		
		// btnGuardar
		btnGuardar = new Button();
		btnGuardar.setCaption("Guardar");
		btnGuardar.setImmediate(true);
		btnGuardar.setWidth("80px");
		btnGuardar.setHeight("-1px");
		horizontalLayout_4.addComponent(btnGuardar);
		horizontalLayout_4.setComponentAlignment(btnGuardar, new Alignment(20));
		
		// btnCerrar
		btnCerrar = new Button();
		btnCerrar.setCaption("Cerrar");
		btnCerrar.setImmediate(true);
		btnCerrar.setWidth("80px");
		btnCerrar.setHeight("-1px");
		horizontalLayout_4.addComponent(btnCerrar);
		horizontalLayout_4.setComponentAlignment(btnCerrar, new Alignment(20));
		
		return horizontalLayout_4;
	}

}
