package com.mindware.vista;

import com.mindware.domain.Contacto;
import com.mindware.domain.Grupo;
import com.mindware.services.ContactoService;
import com.mindware.services.GrupoService;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.shared.ui.MultiSelectMode;
import com.vaadin.ui.*;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import de.steinwedel.messagebox.MessageBox;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AddGrupo extends Window {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TextField edtGrupo;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;
	@AutoGenerated
	private Button btnCerrar;
	@AutoGenerated
	private Button btnGuardar;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	private VerticalLayout verticalButton;
	private Table tableLeft;
	private Table tableRight;
//	private NativeButton btnGuardarGrupo;
	private Button btnMoveLeft;
	private Button btnMoveRight;
	private GrupoService grupoService;
	private ContactoService contactoService;
	final Label current = new Label("Selected: -");

	private List<Object> itemsSelectedLeft  = new ArrayList<Object>();
	private List<Object> itemsSelectedRight = new ArrayList<Object>();

	public AddGrupo() {
		buildMainLayout();

		setContent(mainLayout);
		fillTableLeft();
		fillTableRight();

		selectedTableLeftClick();
		moveToRightTable();

		btnCerrar.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				close();
				
			}
		});
		btnGuardar.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				try {
					grupoService = new GrupoService();
					Date today = new Date();
					Grupo gr = new Grupo();
					gr.setEstado("V"); //VIGENTE
					gr.setFechaCreacion(today);
					gr.setNombreGrupo(edtGrupo.getValue());
					gr.setNumeroMiembros(numeroMiembros());
					gr.setUsuarioId(1); // TODO add user code here
					grupoService.insertGrupo(gr);
					MessageBox.createInfo()
							.withCaption("Registro")
							.withMessage("Grupo creado")
							.open();
				}
				catch (Exception e) {
					MessageBox.createError()
							.withCaption("Error")
							.withMessage("Error al crear el Grupo")
							.withAbortButton()
							.open();
				}

			}
		});
	}



	private void moveToRightTable() {

		btnMoveRight.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {

				if (itemsSelectedLeft.size()>0) {
					for (Object id : itemsSelectedLeft) {
						tableRight.addItem(id);
					}
					tableRight.addItem(new Object[] {"uno","dos","tres","cuatro","cinco", 5},null);

				}
			}
		});


	}

	private void selectedTableLeftClick () {

		tableLeft.addItemClickListener(new ItemClickEvent.ItemClickListener() {
			@Override
			public void itemClick(ItemClickEvent event) {
				Object value = event.getItem(); // event.getItem().getItemProperty("Celular").getValue();//tableLeft.getValue();

				if (!itemsSelectedLeft.contains(value)) {

					itemsSelectedLeft.add(value);
				}
				else {
					itemsSelectedLeft.remove(value);
				}

			}
		});
	}

	private void asignarContacto() {
		btnMoveLeft.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {


			}
		});
	}

	private int numeroMiembros() {
		int i = tableRight.size();
		return i;
	}

	private void fillTableRight() {
		List<Contacto> contactos;
		contactoService = new ContactoService();
		IndexedContainer containerContactoAsignado = new IndexedContainer();

		containerContactoAsignado.addContainerProperty("Celular", String.class, null);
		containerContactoAsignado.addContainerProperty("Contacto", String.class, null);
		containerContactoAsignado.addContainerProperty("Campo1", String.class, null);
		containerContactoAsignado.addContainerProperty("Campo2", String.class, null);
		containerContactoAsignado.addContainerProperty("Campo3", String.class, null);
		containerContactoAsignado.addContainerProperty("ID", Integer.class, null);

		contactos = contactoService.findAvailableContactoActivo();

		if (contactos.size() > 0) {
			for (Contacto contacto : contactos) {
				Item item = containerContactoAsignado.addItem(contacto);
				item.getItemProperty("Celular").setValue(contacto.getCelular());
				item.getItemProperty("Contacto").setValue(contacto.getNombreContacto());
				item.getItemProperty("Campo1").setValue(contacto.getCampo1());
				item.getItemProperty("Campo2").setValue(contacto.getCampo2());
				item.getItemProperty("Campo3").setValue(contacto.getCampo3());
				item.getItemProperty("ID").setValue(contacto.getContactoId());
			}
		}

		tableRight.setContainerDataSource(containerContactoAsignado);



	}

	private void fillTableLeft() {
		List<Contacto> contactos;
		contactoService = new ContactoService();
		IndexedContainer containerContactoDisponible = new IndexedContainer();

		containerContactoDisponible.addContainerProperty("Celular", String.class, null);
		containerContactoDisponible.addContainerProperty("Contacto", String.class, null);
		containerContactoDisponible.addContainerProperty("Campo1", String.class,  null);
		containerContactoDisponible.addContainerProperty("Campo2", String.class, null);
		containerContactoDisponible.addContainerProperty("Campo3", String.class, null);
		containerContactoDisponible.addContainerProperty("ID", Integer.class, null);

		contactos = contactoService.findAvailableContactoActivo();

		if (contactos.size() > 0) {
			for (Contacto contacto : contactos) {
				Item item = containerContactoDisponible.addItem(contacto);
				item.getItemProperty("Celular").setValue(contacto.getCelular());
				item.getItemProperty("Contacto").setValue(contacto.getNombreContacto());
				item.getItemProperty("Campo1").setValue(contacto.getCampo1());
				item.getItemProperty("Campo2").setValue(contacto.getCampo2());
				item.getItemProperty("Campo3").setValue(contacto.getCampo3());
				item.getItemProperty("ID").setValue(contacto.getContactoId());
			}

		}

		tableLeft.setContainerDataSource(containerContactoDisponible);

	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("400px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("400px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1, "top:60.0px;right:-1.0px;left:20.0px;");

		verticalButton = buildVerticalLayout_1();
		mainLayout.addComponent(verticalButton,"top:70.0px;right:-1.0px;left:400.0px;");
		
		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		mainLayout.addComponent(horizontalLayout_4, "top:360.0px;left:18.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Nombre de Grupo:");
		mainLayout.addComponent(label_1, "top:22.0px;left:20.0px;");
		
		// edtGrupo
		edtGrupo = new TextField();
		edtGrupo.setImmediate(false);
		edtGrupo.setWidth("433px");
		edtGrupo.setHeight("24px");
		mainLayout.addComponent(edtGrupo, "top:20.0px;left:123.0px;");

		//btnGuardarGrupo
//		btnGuardarGrupo = new NativeButton();
//		btnGuardarGrupo.setCaption("Guardar Grupo");
//		btnGuardarGrupo.setImmediate(true);
//		btnGuardarGrupo.setWidth("120px");
//		btnGuardarGrupo.setHeight("-1px");
//		mainLayout.addComponent(btnGuardarGrupo,"top:20.0px;left:473.0px;");

		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("260px");
		horizontalLayout_1.setMargin(false);

		// Table left
		tableLeft = new Table();
		//Allow selection Items from  table
		tableLeft.setSelectable(true);
		//tableLeft.setSelectionMode(Grid.SelectionMode.MULTI);
		// Send changes in selection immediately to server.r
		tableLeft.setImmediate(true);
		tableLeft.setMultiSelect(true);
		//desable selected null value
		tableLeft.setMultiSelectMode(MultiSelectMode.SIMPLE);
		tableLeft.setNullSelectionAllowed(false);
		tableLeft.setCaption("Contactos Disponibles");
		tableLeft.setWidth("370px");
		tableLeft.setHeight("250px");
		horizontalLayout_1.addComponent(tableLeft);

		// Table right
		tableRight = new Table();
		//Allow selection Items from  table
		tableRight.setSelectable(true);
		tableRight.setMultiSelect(true);
		// Send changes in selection immediately to server.r
		tableRight.setMultiSelectMode(MultiSelectMode.SIMPLE);
		tableRight.setImmediate(true);
		//desable selected null value
		tableRight.setNullSelectionAllowed(false);

		tableRight.setCaption("Contactos Asignados");
		tableRight.setWidth("370px");
		tableRight.setHeight("250px");
		horizontalLayout_1.addComponent(tableRight);

		return horizontalLayout_1;
	}

	private VerticalLayout buildVerticalLayout_1 () {
		verticalButton = new VerticalLayout();
		verticalButton.setWidth("20%");
		// btnMoveRight
		btnMoveRight = new Button();
		btnMoveRight.setCaption(" >> ");
		btnMoveRight.setImmediate(true);
		verticalButton.addComponent(btnMoveRight);

		// btnMoveLeft
		btnMoveLeft = new Button();
		btnMoveLeft.setCaption(" << ");
		btnMoveLeft.setImmediate(true);
		verticalButton.addComponent(btnMoveLeft);

		return  verticalButton;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("560px");
		horizontalLayout_4.setHeight("40px");
		horizontalLayout_4.setMargin(false);
		
		// btnGuardar
		btnGuardar = new Button();
		btnGuardar.setCaption("Guardar");
		btnGuardar.setImmediate(true);
		btnGuardar.setWidth("80px");
		btnGuardar.setHeight("-1px");
		horizontalLayout_4.addComponent(btnGuardar);
		horizontalLayout_4.setComponentAlignment(btnGuardar, Alignment.MIDDLE_RIGHT);

		// btnCerrar
		btnCerrar = new Button();
		btnCerrar.setCaption("Cerrar");
		btnCerrar.setImmediate(true);
		btnCerrar.setWidth("80px");
		btnCerrar.setHeight("-1px");
		horizontalLayout_4.addComponent(btnCerrar);
		horizontalLayout_4.setComponentAlignment(btnCerrar, Alignment.MIDDLE_RIGHT);
		
		return horizontalLayout_4;
	}


}