package com.mindware.vista;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.*;

public class BandejaEntrada extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TextArea txtmensaje;
	@AutoGenerated
	private Table tblmensaje;
	@AutoGenerated
	private HorizontalLayout layoutHoriz;
	@AutoGenerated
	private NativeButton btnborras;
	@AutoGenerated
	private NativeButton btnresponder;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public BandejaEntrada() {
		buildMainLayout();
		cabeceraTabla();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}
	
	private void cabeceraTabla() {
		tblmensaje.addContainerProperty("De:", String.class, null);
		tblmensaje.addContainerProperty("Mensaje", String.class, null);
		tblmensaje.addContainerProperty("Fecha recivido", String.class, null);
		tblmensaje.setPageLength(20);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("887px");
		mainLayout.setHeight("510px");
		
		// top-level component properties
		setWidth("887px");
		setHeight("510px");
		
		// layoutHoriz
		layoutHoriz = buildLayoutHoriz();
		mainLayout.addComponent(layoutHoriz, "top:10.0px;left:80.0px;");
		
		// tblmensaje
		tblmensaje = new Table();
		tblmensaje.setImmediate(false);
		tblmensaje.setWidth("100.0%");
		tblmensaje.setHeight("238px");
		mainLayout.addComponent(tblmensaje, "top:60.0px;right:171.0px;left:-96.0px;");
		
		// txtmensaje
		txtmensaje = new TextArea();
		txtmensaje.setCaption("Mensaje");
		txtmensaje.setImmediate(false);
		txtmensaje.setWidth("560px");
		txtmensaje.setHeight("-1px");
		mainLayout.addComponent(txtmensaje, "top:324.0px;left:20.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildLayoutHoriz() {
		// common part: create layout
		layoutHoriz = new HorizontalLayout();
		layoutHoriz.setImmediate(false);
		layoutHoriz.setWidth("440px");
		layoutHoriz.setHeight("40px");
		layoutHoriz.setMargin(false);
		
		// btnresponder
		btnresponder = new NativeButton();
		btnresponder.setCaption("Responder");
		btnresponder.setImmediate(true);
		btnresponder.setWidth("106px");
		btnresponder.setHeight("30px");
		layoutHoriz.addComponent(btnresponder);
		
		// btnborras
		btnborras = new NativeButton();
		btnborras.setCaption("Borrar");
		btnborras.setImmediate(true);
		btnborras.setWidth("100px");
		btnborras.setHeight("30px");
		layoutHoriz.addComponent(btnborras);
		
		return layoutHoriz;
	}

}
