package com.mindware.vista;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.*;

import java.util.Date;

public class BandejaSalida extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Table tblSalida;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private NativeButton btnEliminar;
	@AutoGenerated
	private NativeButton btnreenviar;
	@AutoGenerated
	private NativeButton btnenviar;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public BandejaSalida() {
		buildMainLayout();
		cabeceraTabla();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}
	
	private void cabeceraTabla() {
		tblSalida.addContainerProperty("A: ", String.class, null);
		tblSalida.addContainerProperty("Mensaje", String.class, null);
		tblSalida.addContainerProperty("Fecha creacion", Date.class, null);
		tblSalida.addContainerProperty("Fecha envio", Date.class, null);
		tblSalida.setPageLength(20);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1, "top:20.0px;left:100.0px;");
		
		// tblSalida
		tblSalida = new Table();
		tblSalida.setCaption("Mensajes a Enviar");
		tblSalida.setImmediate(false);
		tblSalida.setWidth("100.0%");
		tblSalida.setHeight("100.0%");
		mainLayout.addComponent(tblSalida, "top:80.0px;right:54.0px;bottom:118.0px;left:12.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("440px");
		horizontalLayout_1.setHeight("40px");
		horizontalLayout_1.setMargin(false);
		
		// btnenviar
		btnenviar = new NativeButton();
		btnenviar.setCaption("Enviar");
		btnenviar.setImmediate(false);
		btnenviar.setWidth("90px");
		btnenviar.setHeight("40px");
		horizontalLayout_1.addComponent(btnenviar);
		
		// btnreenviar
		btnreenviar = new NativeButton();
		btnreenviar.setCaption("Reenviar");
		btnreenviar.setImmediate(false);
		btnreenviar.setWidth("90px");
		btnreenviar.setHeight("40px");
		horizontalLayout_1.addComponent(btnreenviar);
		
		// btnEliminar
		btnEliminar = new NativeButton();
		btnEliminar.setCaption("Eliminar");
		btnEliminar.setImmediate(false);
		btnEliminar.setWidth("90px");
		btnEliminar.setHeight("40px");
		horizontalLayout_1.addComponent(btnEliminar);
		
		return horizontalLayout_1;
	}

}
