package com.mindware.vista;

import com.mindware.domain.Mensaje;
import com.mindware.services.MensajeService;
import com.mindware.util.SendSms;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.shared.ui.MultiSelectMode;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.*;
import de.steinwedel.messagebox.MessageBox;

import java.util.ArrayList;
import java.util.List;

import org.smslib.Service;

public class BandejaSalida extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Table tblSalida;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private NativeButton btnEliminar;
	@AutoGenerated
	private NativeButton btnreenviar;
	@AutoGenerated
	private NativeButton btnenviar;
	private NativeButton btnCargarMensajes;
	private Label titulo;
	private MensajeService mensajeService;
//	private ProgressBar progressBar;
	private SendSms sendSms;

	public BandejaSalida() {
		buildMainLayout();
		cabeceraTabla();
		setCompositionRoot(mainLayout);

		//Llena bandeja de salida

		cargarMensajes();
		
		enviarMensaje();

	}

	private List<Mensaje> mensajes() {
		ArrayList<List<String>> arregloMensajes = new ArrayList<List<String>>();
		IndexedContainer container = (IndexedContainer) tblSalida.getContainerDataSource();
		List<Mensaje> listaMensajes = (List<Mensaje>) container.getItemIds();

		return listaMensajes;
	}
	//////////////////////////////////////
//    public class Worker extends Thread {
//        int current = 1;
//        public final static int MAX = 10;
// 
//        @Override
//        public void run() {
//            for (; current <= MAX; current++) {
//                try {
//                    Thread.sleep(1000);
//                } catch (final InterruptedException e) {
//                    e.printStackTrace();
//                }
//                synchronized (UI.getCurrent()) {
//                    processed();
//                }
//            }
//        }
// 
//        public int getCurrent() {
//            return current;
//        }
// 
//    }
//    
//   
//	public final void processed() {
//    	 
//        final int i = 1;
//        if (i == Worker.MAX) {
//            UI.getCurrent().setPollInterval(-1);
//          //  startButton.setEnabled(true);
//            progressBar.setValue(0f);
//            progressBar.setVisible(!progressBar.isIndeterminate());
//        } else {
//            progressBar.setValue((float) i / Worker.MAX);
//        }
//    }
//    ////////////////////////////
	
	private void enviarMensaje()  {

		btnenviar.addClickListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(Button.ClickEvent clickEvent) {
				try {
					//List<Mensaje> msg = new ArrayList<>();
					if (!mensajes().isEmpty()) {
						
						if (sendSms==null)  {
//			                Worker worker = new Worker();
//			                worker.start();
//			                progressBar.setValue(0f);
//			                progressBar.setVisible(true);
							btnenviar.setEnabled(false);
							sendSms = new SendSms("modem.com6", "COM6", 9600, "Huawei", "E303");
							//UI.getCurrent().setPollInterval(500);
							Service.getInstance().startService();
							for (Mensaje mensaje : mensajes()) {
								
								sendSms.sendMessage(mensaje.getMensaje(), mensaje.getCelular(), mensaje.getMensajeId(), mensaje.getNumeroIntentos());
								
								
							}
							Service.getInstance().stopService();
							
							sendSms.removeGateway();
							sendSms = null;
							datosBandejaSalida();
							MessageBox.createInfo()
							.withCaption("Envio mensajes")
							.withMessage("Mensajes enviados")
							.open();
							btnenviar.setEnabled(true);
							
							//worker.stop();
					  } else {
							
							MessageBox.createInfo()
							.withCaption("Envio mensajes")
							.withMessage("Existen mensajes en proceso de envio, intente mas adelante")
							.open();
							
					  }
						
					} else {
						MessageBox.createInfo()
								.withCaption("Envio mensajes")
								.withMessage("No se tienen mensajes para enviar")
								.open();
					}
				}
				catch (Exception e) {
					e.printStackTrace();
				}


			}
		});
		
	btnreenviar.addClickListener(new Button.ClickListener() {
		@Override
		public void buttonClick(Button.ClickEvent clickEvent) {
			try {
				List<Mensaje> msg = new ArrayList<>();
				msg = mensajes();
				if (!msg.isEmpty()) {
					
					if (sendSms==null)  {
						sendSms = new SendSms("modem.com6", "COM6", 9600, "Huawei", "E303");
						Service.getInstance().startService();
						sendSms.sendMessages(msg);
						Service.getInstance().stopService();
						sendSms.removeGateway();
						sendSms = null;
						datosBandejaSalida();
						
						MessageBox.createInfo()
						.withCaption("Envio mensajes")
						.withMessage("Mensajes enviados")
						.open();
					} 	else {
						MessageBox.createInfo()
						.withCaption("Envio mensajes")
						.withMessage("Existen mensajes en proceso de envio, intente mas adelante")
						.open();
					}
					
				} else {
					MessageBox.createInfo()
							.withCaption("Envio mensajes")
							.withMessage("No se tienen mensajes para enviar")
							.open();
				}
			}
			catch (Exception e) {
				e.printStackTrace();
			}
		}
		
	});
		

		

	}
	
	private void cargarMensajes() {
		btnCargarMensajes.addClickListener(new Button.ClickListener() {
			@Override
			public void buttonClick(Button.ClickEvent event) {
				datosBandejaSalida();
			}
		});

	}


	public void datosBandejaSalida() { //TODO : poner parametros para usuario y estado mensaje
		mensajeService = new MensajeService();
		llenarBandejaSalida(mensajeService.findMensajesUsuario(1,"F")); 
	
	}
	
	private void cabeceraTabla() {

		tblSalida.addContainerProperty("ID", Integer.class, null);
		tblSalida.addContainerProperty("Celular", String.class, null);
		tblSalida.addContainerProperty("Nombre Contacto", String.class, null);
		tblSalida.addContainerProperty("Mensaje", String.class, null);
		tblSalida.addContainerProperty("Longitud mensaje", Integer.class, null);
		tblSalida.setPageLength(20);
	}

	private void llenarBandejaSalida(List<Mensaje> mensajes) {
		IndexedContainer containerMensaje = new IndexedContainer();

		containerMensaje.addContainerProperty("ID", Integer.class,"");
		containerMensaje.addContainerProperty("Celular", String.class,"");
		containerMensaje.addContainerProperty("Nombre", String.class,"");
		containerMensaje.addContainerProperty("Mensaje", String.class,"");
		containerMensaje.addContainerProperty("Longitud", Integer.class,"");
		if (mensajes.size() > 0) {
			

			for(Mensaje mensaje : mensajes) {
				Item item = containerMensaje.addItem(mensaje);
				item.getItemProperty("ID").setValue(mensaje.getMensajeId());
				item.getItemProperty("Celular").setValue(mensaje.getCelular());
				item.getItemProperty("Nombre").setValue(mensaje.getNombre());
				item.getItemProperty("Mensaje").setValue(mensaje.getMensaje());
				item.getItemProperty("Longitud").setValue(mensaje.getLongitudSms());
			}
			tblSalida.setContainerDataSource(containerMensaje);

		} else {
			
			tblSalida.setContainerDataSource(containerMensaje);
		}
		
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

//		//ProgressBar
//		progressBar = new ProgressBar();
//		progressBar.setIndeterminate(true);
//		progressBar.setVisible(true);
//		mainLayout.addComponent(progressBar);//,"top:100.0px;right:84.0px;bottom:118.0px;left:12.0px;");
		
		// titulo
		titulo = new Label();
		titulo.setImmediate(false);
		titulo.setWidth("560px");
		titulo.setHeight("60px");
		titulo.setValue("Bandeja de Salida");
		titulo.setContentMode(ContentMode.HTML);
		titulo.setStyleName("titulo");
		mainLayout.addComponent(titulo);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1, "top:45.0px;left:100.0px;");
		
		// tblSalida
		tblSalida = new Table();
		tblSalida.setCaption("Mensajes a Enviar");
		tblSalida.setImmediate(false);
		tblSalida.setWidth("100.0%");
		tblSalida.setHeight("100.0%");
		tblSalida.setSelectable(true);
		tblSalida.setMultiSelectMode(MultiSelectMode.SIMPLE);
		tblSalida.setMultiSelect(true);
		mainLayout.addComponent(tblSalida, "top:90.0px;right:54.0px;bottom:118.0px;left:12.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("40px");
		horizontalLayout_1.setMargin(false);

		// btnCargarMensajes
		btnCargarMensajes = new NativeButton();
		btnCargarMensajes.setCaption("Cargar Mensajes");
		btnCargarMensajes.setImmediate(false);
		btnCargarMensajes.setWidth("130px");
		btnCargarMensajes.setHeight("40px");
		horizontalLayout_1.addComponent(btnCargarMensajes);
		horizontalLayout_1.setComponentAlignment(btnCargarMensajes, new Alignment(20));

		// btnenviar
		btnenviar = new NativeButton();
		btnenviar.setCaption("Enviar");
		btnenviar.setImmediate(false);
		btnenviar.setWidth("160px");
		btnenviar.setHeight("37px");
		horizontalLayout_1.addComponent(btnenviar);
		horizontalLayout_1.setComponentAlignment(btnenviar, new Alignment(20));

		
		// btnreenviar
		btnreenviar = new NativeButton();
		btnreenviar.setCaption("Reenviar");
		btnreenviar.setImmediate(false);
		btnreenviar.setWidth("160px");
		btnreenviar.setHeight("37px");
		horizontalLayout_1.addComponent(btnreenviar);
		horizontalLayout_1.setComponentAlignment(btnreenviar, new Alignment(20));

		
		// btnEliminar
		btnEliminar = new NativeButton();
		btnEliminar.setCaption("Eliminar");
		btnEliminar.setImmediate(false);
		btnEliminar.setWidth("160px");
		btnEliminar.setHeight("37px");
		horizontalLayout_1.addComponent(btnEliminar);
		horizontalLayout_1.setComponentAlignment(btnEliminar, new Alignment(20));
		
		return horizontalLayout_1;
	}
	
//	private void sendMessage() throws Exception {
//	    OutboundNotification outboundNotification = new OutboundNotification();
//	    System.out.println("Sample of Send message from a serial gsm modem.");
//	    System.out.println(Library.getLibraryDescription());
//	    System.out.println("Version: " + Library.getLibraryVersion());
//	    SerialModemGateway gateway = new SerialModemGateway("modem.com6", "COM6", 9600, "Huawei", "E303");
//
//	    gateway.setInbound(false);
//	    gateway.setOutbound(true);
//
//	    try {
//	    Service.getInstance().setOutboundMessageNotification(outboundNotification);
//	    Service.getInstance().addGateway(gateway);
//	    Service.getInstance().startService();
//	    } catch (Exception e) {
//	    	System.out.println("Error: " + e);
//	    }
//
//	    System.out.println();
//	    System.out.println("Modem Information:");
//	    System.out.println("  Manufacturer: " + gateway.getManufacturer());
//	    System.out.println("  Model: " + gateway.getModel());
//	    System.out.println("  Serial No: " + gateway.getSerialNo());
//	    System.out.println("  SIM IMSI: " + gateway.getImsi());
//	    System.out.println("  Signal Level: " + gateway.getSignalLevel()
//	            + " dBm");
//	    System.out.println("  Battery Level: " + gateway.getBatteryLevel()
//	            + "%");
//
//	    // Send a message synchronously.
//	    OutboundMessage msg = new OutboundMessage("+59179707808",
//	            "Mensaje de Prueba");
//
////	    Service srvice = Service.getInstance();
//	    Service.getInstance().sendMessage(msg);
//	    System.out.println(msg);
//
//
//	    Service.getInstance().stopService();
//	}
//
//	private class OutboundNotification implements IOutboundMessageNotification {
//	    public void process(AGateway gateway, OutboundMessage msg) {
//	        System.out.println("Outbound handler called from Gateway: "
//	                + gateway.getGatewayId());
//	        System.out.println(msg);
//	    }
//	}
	

}
