package com.mindware.vista;


import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Validator.InvalidValueException;
import com.vaadin.data.validator.IntegerRangeValidator;
import com.vaadin.ui.*;


public class confCobros extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,8","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private NativeButton btnCerrar;
	@AutoGenerated
	private NativeButton btnGuardar;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private TextField txtEmail;
	@AutoGenerated
	private TextField txtDiasAntesTercerAviso;
	@AutoGenerated
	private CheckBox chkTercerEnvio;
	@AutoGenerated
	private CheckBox chkSegundoEnvio;
	@AutoGenerated
	private TextField txtDiasAntesSegundoAviso;
	@AutoGenerated
	private TextField txtDiasAntesPrimerAviso;


	public confCobros() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		
	}

	public void ValidaDatos(){
		
		//Valida el dia del segundo aviso
		try {
			txtDiasAntesPrimerAviso.addValidator(new IntegerRangeValidator("{0 } no es un numero valido", 1, 31));
			txtDiasAntesPrimerAviso.validate(); 
		}
		catch (InvalidValueException e) {
			 Notification.show(e.getMessage());
		}
		
		//Valida el dia de segundo aviso
		if (chkSegundoEnvio.equals(true)) {
			try {
				txtDiasAntesSegundoAviso.addValidator(new IntegerRangeValidator("{0 } no es un numero valido", 1, 31));
				txtDiasAntesSegundoAviso.validate(); 
			}
			catch (InvalidValueException e) {
				Notification.show(e.getMessage());
			}
		}
		//Valida el dia de tercer aviso
		if (chkTercerEnvio.equals(true)) {
			try {
				txtDiasAntesTercerAviso.addValidator(new IntegerRangeValidator("{0 } no es un numero valido", 1, 31));
				txtDiasAntesTercerAviso.validate(); 
			}
			catch (InvalidValueException e) {
				Notification.show(e.getMessage());
			}
		}
	
		
	}

	@AutoGenerated
	public AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// txtDiasAntesPrimerAviso
		txtDiasAntesPrimerAviso = new TextField();
		txtDiasAntesPrimerAviso.setImmediate(false);
		txtDiasAntesPrimerAviso.setWidth("64px");
		txtDiasAntesPrimerAviso.setHeight("-1px");
		txtDiasAntesPrimerAviso.setRequired(true);
		mainLayout.addComponent(txtDiasAntesPrimerAviso, "top:80.0px;left:264.0px;");
		
		// txtDiasAntesSegundoAviso
		txtDiasAntesSegundoAviso = new TextField();
		txtDiasAntesSegundoAviso.setImmediate(false);
		txtDiasAntesSegundoAviso.setWidth("65px");
		txtDiasAntesSegundoAviso.setHeight("-1px");
		mainLayout.addComponent(txtDiasAntesSegundoAviso, "top:120.0px;left:263.0px;");
		
		// chkSegundoEnvio
		chkSegundoEnvio = new CheckBox();
		chkSegundoEnvio.setCaption("Activado");
		chkSegundoEnvio.setImmediate(false);
		chkSegundoEnvio.setWidth("-1px");
		chkSegundoEnvio.setHeight("-1px");
		mainLayout.addComponent(chkSegundoEnvio, "top:120.0px;left:349.0px;");
		
		// chkTercerEnvio
		chkTercerEnvio = new CheckBox();
		chkTercerEnvio.setCaption("Activado");
		chkTercerEnvio.setImmediate(false);
		chkTercerEnvio.setWidth("-1px");
		chkTercerEnvio.setHeight("-1px");
		mainLayout.addComponent(chkTercerEnvio, "top:161.0px;left:349.0px;");
		
		// txtDiasAntesTercerAviso
		txtDiasAntesTercerAviso = new TextField();
		txtDiasAntesTercerAviso.setImmediate(false);
		txtDiasAntesTercerAviso.setWidth("64px");
		txtDiasAntesTercerAviso.setHeight("-1px");
		mainLayout.addComponent(txtDiasAntesTercerAviso, "top:160.0px;left:264.0px;");
		
		// txtEmail
		txtEmail = new TextField();
		txtEmail.setImmediate(false);
		txtEmail.setWidth("156px");
		txtEmail.setHeight("-1px");
		mainLayout.addComponent(txtEmail, "top:200.0px;left:263.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("100.0%");
		label_1.setHeight("24px");
		label_1.setValue("Primer envio dias antes fecha de cobro:");
		mainLayout.addComponent(label_1, "top:80.0px;right:409.0px;left:27.0px;");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Segundo envio dias antes fecha de cobro:");
		mainLayout.addComponent(label_2, "top:120.0px;left:13.0px;");
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Tercer envio dias antes fecha de cobro:");
		mainLayout.addComponent(label_3, "top:165.0px;left:27.0px;");
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("Email reporte de carga diaria:");
		mainLayout.addComponent(label_4, "top:200.0px;left:81.0px;");
		
		// btnGuardar
		btnGuardar = new NativeButton();
		btnGuardar.setCaption("Guardar");
		btnGuardar.setImmediate(true);
		btnGuardar.setWidth("-1px");
		btnGuardar.setHeight("-1px");
		mainLayout.addComponent(btnGuardar, "top:240.0px;left:120.0px;");
		
		// btnCerrar
		btnCerrar = new NativeButton();
		btnCerrar.setCaption("Cerrar");
		btnCerrar.setImmediate(true);
		btnCerrar.setWidth("69px");
		btnCerrar.setHeight("-1px");
		mainLayout.addComponent(btnCerrar, "top:240.0px;left:267.0px;");
		
		return mainLayout;
	}
    
	
}
