package com.mindware.vista;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.*;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;


@SuppressWarnings("serial")
public class ListaContactos extends CustomComponent{
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Table tbl_contactos;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private NativeButton btnEditar;
	@AutoGenerated
	private NativeButton btnImportar;
	@AutoGenerated
	private NativeButton btnNuevoContacto;
	Window mainwindow;  // Reference to main window
	Window mywindow;    // The window to be opened
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ListaContactos() {
		
		buildMainLayout();
		setCompositionRoot(mainLayout);
        llenarContactos("");
        
        btnNuevoContacto.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				
				AddContacto addContacto = new AddContacto();
				addContacto.setModal(true);
				addContacto.setWidth("600px");
				addContacto.setHeight("450px");
				addContacto.center();
				//windowAddContacto.setContent(addContacto);
				
				UI.getCurrent().addWindow(addContacto);
			}
		});	
        
        btnImportar.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				
				CargarArchivo cargarArchivo = new CargarArchivo();
				cargarArchivo.setModal(true);
				cargarArchivo.setWidth("700px");
				cargarArchivo.setHeight("700px");
				cargarArchivo.center();
				
				UI.getCurrent().addWindow(cargarArchivo);
				
			}
		});
        
	}
	
	private void llenarContactos( String nombre ) {
		tbl_contactos.addContainerProperty("nombre_cliente", String.class, nombre);
		tbl_contactos.addContainerProperty("telefono", String.class, "Tel�fono");
		tbl_contactos.addContainerProperty("campo1", String.class, "Campo 1");
		tbl_contactos.addContainerProperty("campo2", String.class, "Campo 2");
		tbl_contactos.addContainerProperty("campo3", String.class, "Campo 3");
		tbl_contactos.addContainerProperty("campo4", String.class, "Campo 4");
		tbl_contactos.addContainerProperty("campo5", String.class, "Campo 5");
		tbl_contactos.addContainerProperty("campo6", String.class, "Campo 6");
	
		
	}
	
	

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		mainLayout.addComponent(gridLayout_1, "top:11.0px;right:13.0px;left:9.0px;");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1, "top:79.0px;left:9.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		gridLayout_1.setHeight("50px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setColumns(3);
		gridLayout_1.setRows(2);
		
		// btnNuevoContacto
		btnNuevoContacto = new NativeButton();
		btnNuevoContacto.setCaption("Nuevo");
		btnNuevoContacto.setImmediate(true);
		btnNuevoContacto.setWidth("120px");
		btnNuevoContacto.setHeight("-1px");
		gridLayout_1.addComponent(btnNuevoContacto, 0, 0);
		
		// btnImportar
		btnImportar = new NativeButton();
		btnImportar.setCaption("Importar");
		btnImportar.setImmediate(true);
		btnImportar.setWidth("120px");
		btnImportar.setHeight("-1px");
		gridLayout_1.addComponent(btnImportar, 1, 0);
		
		// btnEditar
		btnEditar = new NativeButton();
		btnEditar.setCaption("Editar");
		btnEditar.setImmediate(true);
		btnEditar.setWidth("120px");
		btnEditar.setHeight("-1px");
		gridLayout_1.addComponent(btnEditar, 2, 0);
		
		return gridLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("252px");
		horizontalLayout_1.setMargin(false);
		
		// tbl_contactos
		tbl_contactos = new Table();
		tbl_contactos.setImmediate(false);
		tbl_contactos.setWidth("100.0%");
		tbl_contactos.setHeight("100.0%");
		horizontalLayout_1.addComponent(tbl_contactos);
		
		return horizontalLayout_1;
	}

	

}
