package com.mindware.vista;

import com.mindware.sms.smsUI;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.event.ShortcutListener;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.*;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.Button.ClickEvent;


public class LoginUI extends CustomComponent implements ClickListener{

	/*- VaadinEditorProperties={"grid":"RegularGrid,8","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout borde;
	@AutoGenerated
	private NativeButton btnSalir;
	@AutoGenerated
	private NativeButton btnIngresar;
	@AutoGenerated
	private PasswordField txtClave;
	@AutoGenerated
	private TextField txtUsuario;
	@AutoGenerated
	private Label label_6;
	@AutoGenerated
	private Label label_5;
	private Label lblMensaje;

	public LoginUI() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
        postBuild();
		
	}

	private void postBuild(){
		this.btnIngresar.addClickListener((ClickListener)this);

		this.txtUsuario.addShortcutListener(new ShortcutListener("",KeyCode.ENTER,null) {
			@Override
			public void handleAction(Object sender, Object target) {
				logeo();
			}
		} );

		this.txtClave.addShortcutListener(new ShortcutListener("",KeyCode.ENTER,null) {
			@Override
			public void handleAction(Object sender, Object target) {
				logeo();
			}
		});
	}

	private void logeo() {
		if (validarDatos()) {
			if (this.txtUsuario.getValue().equals("admin") && this.txtClave.getValue().equals("123")) {
				((smsUI) UI.getCurrent()).cargarMenu();
			}
		}
	}

	private boolean validarDatos(){
		boolean respuesta=true;
		if(this.txtUsuario.getValue().toString().length()==0){
			this.lblMensaje.setValue("<b>Ingrese usuario</b>");
			return false;
		}else{
			this.lblMensaje.setValue("");
		}
		if(this.txtClave.getValue().toString().length()==0){
			this.lblMensaje.setValue("<b>Ingrese Clave</b>");
			return false;
		}else{
			this.lblMensaje.setValue("");
		}
		return respuesta;
	}
	@Override
	public void buttonClick(ClickEvent event ) {
		if (event.getSource()==this.btnIngresar) {
			logeo();
			}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// borde
		borde = buildBorde();
		mainLayout.addComponent(borde, "top:180.0px;left:328.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildBorde() {
		// common part: create layout
		borde = new AbsoluteLayout();
		borde.setStyleName("Reindeer.LAYOUT_BLUE");
		borde.setImmediate(false);
		borde.setWidth("400px");
		borde.setHeight("182px");
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("-1px");
		label_5.setHeight("-1px");
		label_5.setValue("Usuario:");
		borde.addComponent(label_5, "top:0.0px;left:89.0px;");
		
		// label_6
		label_6 = new Label();
		label_6.setImmediate(false);
		label_6.setWidth("-1px");
		label_6.setHeight("-1px");
		label_6.setValue("Clave:");
		borde.addComponent(label_6, "top:50.0px;left:102.0px;");

		// lblMensaje
		lblMensaje = new Label();
		lblMensaje.setImmediate(false);
		lblMensaje.setWidth("-1px");
		lblMensaje.setHeight("-1px");
		lblMensaje.setValue("");
		lblMensaje.setContentMode(ContentMode.HTML);
		borde.addComponent(lblMensaje, "top:90.0px;left:102.0px;");
		
		// txtUsuario
		txtUsuario = new TextField();
		txtUsuario.setImmediate(false);
		txtUsuario.setWidth("-1px");
		txtUsuario.setHeight("-1px");
		borde.addComponent(txtUsuario, "top:0.0px;left:144.0px;");
		
		// txtClave
		txtClave = new PasswordField();
		txtClave.setImmediate(false);
		txtClave.setWidth("-1px");
		txtClave.setHeight("-1px");
		borde.addComponent(txtClave, "top:50.0px;left:144.0px;");
		
		// btnIngresar
		btnIngresar = new NativeButton();
		btnIngresar.setCaption("Ingresar");
		btnIngresar.setImmediate(true);
		btnIngresar.setWidth("100px");
		btnIngresar.setHeight("-1px");
		borde.addComponent(btnIngresar, "top:110.0px;left:150.0px;");
		
		// btnSalir
//		btnSalir = new NativeButton();
//		btnSalir.setCaption("Salir");
//		btnSalir.setImmediate(true);
//		btnSalir.setWidth("100px");
//		btnSalir.setHeight("-1px");
//		borde.addComponent(btnSalir, "top:134.0px;left:236.0px;");
		
		return borde;
	}

}
